export const User = [
  {
    id: 1,
    name: "Bilol",
    lname: "Doe",
    age: 20,
    country: "USA",
    gender: "male",
  },
  {
    id: 2,
    name: "Amina",
    lname: "Smith",
    age: 22,
    country: "Canada",
    gender: "female",
  },
  {
    id: 3,
    name: "John",
    lname: "Brown",
    age: 25,
    country: "UK",
    gender: "male",
  },
  {
    id: 4,
    name: "Sara",
    lname: "Lee",
    age: 19,
    country: "Australia",
    gender: "female",
  },
  {
    id: 5,
    name: "Hiroshi",
    lname: "Tanaka",
    age: 30,
    country: "Japan",
    gender: "male",
  },
  {
    id: 6,
    name: "Fatima",
    lname: "Ali",
    age: 27,
    country: "UAE",
    gender: "female",
  },
  {
    id: 7,
    name: "Carlos",
    lname: "Garcia",
    age: 24,
    country: "Mexico",
    gender: "male",
  },
  {
    id: 8,
    name: "Anna",
    lname: "Kowalska",
    age: 21,
    country: "Poland",
    gender: "female",
  },
  {
    id: 9,
    name: "Liam",
    lname: "Wilson",
    age: 23,
    country: "New Zealand",
    gender: "male",
  },
  {
    id: 10,
    name: "Elena",
    lname: "Ivanova",
    age: 26,
    country: "Russia",
    gender: "female",
  },
  {
    id: 11,
    name: "Ahmed",
    lname: "Hassan",
    age: 28,
    country: "Egypt",
    gender: "male",
  },
  {
    id: 12,
    name: "Zara",
    lname: "Khan",
    age: 22,
    country: "Pakistan",
    gender: "female",
  },
  {
    id: 13,
    name: "Noah",
    lname: "Müller",
    age: 31,
    country: "Germany",
    gender: "male",
  },
  {
    id: 14,
    name: "Isabella",
    lname: "Rossi",
    age: 20,
    country: "Italy",
    gender: "female",
  },
  {
    id: 15,
    name: "David",
    lname: "Nguyen",
    age: 29,
    country: "Vietnam",
    gender: "male",
  },
  {
    id: 16,
    name: "Mei",
    lname: "Chen",
    age: 24,
    country: "China",
    gender: "female",
  },
  {
    id: 17,
    name: "Jean",
    lname: "Dupont",
    age: 27,
    country: "France",
    gender: "male",
  },
  {
    id: 18,
    name: "Maria",
    lname: "Silva",
    age: 26,
    country: "Brazil",
    gender: "female",
  },
  {
    id: 19,
    name: "Igor",
    lname: "Petrov",
    age: 25,
    country: "Ukraine",
    gender: "male",
  },
  {
    id: 20,
    name: "Yuki",
    lname: "Sato",
    age: 23,
    country: "Japan",
    gender: "female",
  },
];
